"use strict";
const assert = require("assert");
const fs = require("fs");
const path = require("path");
const root = path.resolve(__dirname, "..");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "manifest.json"), "utf8"));
assert.strictEqual(manifest.author, "Jens Kowalsky, 3-5 Power Electronics GmbH");
assert.strictEqual(manifest.browser_specific_settings.gecko.id, "m365-calendar-for-thunderbird@3-5pe.com");
assert.ok(manifest.permissions.includes("sensitiveDataUpload"));
console.log("V2.34 public branding/ATN manifest contract passed");
