"use strict";
const assert = require("assert");
const fs = require("fs");
const path = require("path");
const api = fs.readFileSync(path.resolve(__dirname,"../experiments/nativeCalendar/api.js"),"utf8");
assert.ok(api.includes('const NATIVE_MAPPING_VERSION = "2.32-full-cache-readopt"'));
assert.ok(api.includes('if (safeString(item?.getProperty?.("X-M365-NATIVE-MAP-VERSION")) !== NATIVE_MAPPING_VERSION) return false;'));
assert.ok(api.includes('if (mappingRepair) {'));
assert.ok(api.includes('stats.visibilityRepairs += 1'));
assert.ok(api.includes('cacheOtherMeetings'));
console.log("V2.30 all non-online native visibility migration contract OK");
