"use strict";
const fs=require("fs"),path=require("path"),assert=require("assert");
const root=path.resolve(__dirname,"..");
const api=fs.readFileSync(path.join(root,"experiments","nativeCalendar","api.js"),"utf8");
const bg=fs.readFileSync(path.join(root,"background.js"),"utf8");
const ui=fs.readFileSync(path.join(root,"calendar","calendar.js"),"utf8");
assert.ok(api.includes("const nativeProviderQueryStats"),"provider getItems diagnostics missing");
assert.ok(api.includes("recordProviderGetItems(this, aFilter, aCount, aRangeStart, aRangeEnd)"),"real provider getItems calls are not recorded");
assert.ok(api.includes("getItemsAsArray(filter, count, rangeStart, rangeEnd)"),"bounded mirror result count missing");
assert.ok(api.includes("providerMirrorItemDescriptor"),"exact provider mirror item summaries missing");
assert.ok(api.includes("mirrorItems: []"),"provider query result item list missing");
assert.ok(api.includes("mirrorTruncated"),"provider query result truncation marker missing");
assert.ok(api.includes("async function collectCurrentViewDiagnostics"),"current Thunderbird view diagnostics missing");
assert.ok(api.includes("diagnosticRenderedCalendarItems"),"best-effort rendered item scan missing");
assert.ok(api.includes('layer: "cached-wrapper"') || api.includes('"cached-wrapper"'),"cached wrapper range query missing");
assert.ok(api.includes('"uncached-provider"'),"uncached provider range query missing");
assert.ok(api.includes('"offline-storage"'),"offline storage range query missing");
assert.ok(api.includes("providerQueryStats: providerQuerySnapshot()"),"provider query snapshot not exported");
assert.ok(api.includes("currentViewDiagnostics,"),"current view diagnostics not exported");
assert.ok(bg.includes("currentViewWrapperOccurrences"),"summary lacks wrapper occurrence count");
assert.ok(bg.includes("currentViewStorageOccurrences"),"summary lacks storage occurrence count");
assert.ok(ui.includes('name: "native_current_view.json"'),"diagnostic ZIP lacks current view JSON");
assert.ok(ui.includes('name: "native_provider_queries.json"'),"diagnostic ZIP lacks provider query JSON");
console.log("native Month/Multiweek deep diagnostics V2.49: OK");
