"use strict";
const fs=require("fs"),path=require("path"),assert=require("assert");
const root=path.resolve(__dirname,"..");
const api=fs.readFileSync(path.join(root,"experiments/nativeCalendar/api.js"),"utf8");
const schema=JSON.parse(fs.readFileSync(path.join(root,"experiments/nativeCalendar/schema.json"),"utf8"));
const bg=fs.readFileSync(path.join(root,"background.js"),"utf8");
assert.ok(schema[0].functions.some(f=>f.name==="activate"),"schema must expose provider activation");
assert.ok(api.includes("async activate()"),"Experiment API activate method missing");
assert.ok(api.includes('return _m365NativeProviderCall(extension, "activate")'));
assert.ok(api.includes("async function activate(extension)"),"runtime provider activation missing");
const autoStart=bg.indexOf("async function runNativeAutoSync");
const autoEnd=bg.indexOf("\nfunction nativeApiIfLoaded",autoStart);
const auto=bg.slice(autoStart,autoEnd);
assert.ok(auto.indexOf("nativeApi.activate") < auto.indexOf("authStatus()"),"provider must activate before Microsoft auth status can short-circuit sync");
const statusStart=bg.indexOf("async function nativeStatus");
const statusEnd=bg.indexOf("\nasync function",statusStart+10);
const status=bg.slice(statusStart,statusEnd>statusStart?statusEnd:undefined);
assert.ok(status.includes("api?.activate"),"settings/status path must also repair persisted dummy calendars");
console.log("native provider activation V2.22: OK");
