"use strict";
const fs=require("fs"),path=require("path"),assert=require("assert");
const root=path.resolve(__dirname,"..");
const api=fs.readFileSync(path.join(root,"experiments","nativeCalendar","api.js"),"utf8");
const schema=JSON.parse(fs.readFileSync(path.join(root,"experiments","nativeCalendar","schema.json"),"utf8"));
assert.ok(api.includes("async function reloadOpenCalendarViews(reason = \"manual\")"));
assert.ok(api.includes("Services.wm.getEnumerator(null)"));
assert.ok(api.includes("view.refreshItems(true)"));
assert.ok(api.includes('return "refreshItems(force)"'));
assert.ok(api.includes('return "goToDay(legacy-fallback)"'));
assert.ok(api.includes("Services.tm.dispatchToMainThread"));
assert.ok(api.includes("calendar-main-in-composite"));
assert.ok(api.includes("const refreshed = await reloadOpenCalendarViews(reason);"));
assert.ok(schema[0].functions.some(f=>f.name==="reloadViews"));
console.log("native current-view safe item refresh V2.46: OK");
