"use strict";
const fs=require("fs"), path=require("path"), assert=require("assert");
const root=path.resolve(__dirname,"..");
const bg=fs.readFileSync(path.join(root,"background.js"),"utf8");
const ui=fs.readFileSync(path.join(root,"calendar/calendar.js"),"utf8");
const html=fs.readFileSync(path.join(root,"calendar/calendar.html"),"utf8");
const confirmJs=fs.readFileSync(path.join(root,"confirm/confirm.js"),"utf8");
assert.ok(bg.includes("confirmOutgoingMessages: true"),"default safety switch must be enabled");
assert.ok(bg.includes("clean.confirmOutgoingMessages = clean.confirmOutgoingMessages !== false"),"config normalization missing");
assert.ok(bg.includes("async function requestOutgoingConfirmation"),"central confirmation gate missing");
assert.ok(bg.includes('kind: "meetingInvite"'),"meeting invitation confirmation missing");
assert.ok(bg.includes('kind: "meetingUpdate"'),"meeting update confirmation missing");
assert.ok(bg.includes('kind: "meetingCancellation"'),"meeting cancellation confirmation missing");
assert.ok(bg.includes("outgoingResponseKind(response)"),"RSVP confirmation missing");
assert.ok(bg.includes('case "getOutgoingConfirmation"'),"confirmation popup read channel missing");
assert.ok(bg.includes('case "resolveOutgoingConfirmation"'),"confirmation popup result channel missing");
assert.ok(html.includes('id="confirmOutgoingMessagesCheck"'),"settings switch missing");
assert.ok(ui.includes("els.confirmOutgoingMessagesCheck.checked = state.config.confirmOutgoingMessages !== false"),"settings load missing");
assert.ok(ui.includes("confirmOutgoingMessages: els.confirmOutgoingMessagesCheck.checked"),"settings save missing");
assert.ok(confirmJs.includes('action: "resolveOutgoingConfirmation"'),"confirmation popup cannot resolve action");
console.log("V2.35 outgoing-message confirmation contract passed");
