"use strict";
const assert = require("assert");
const fs = require("fs");
const path = require("path");
const root = path.join(__dirname, "..");
const bg = fs.readFileSync(path.join(root, "background.js"), "utf8");
const ui = fs.readFileSync(path.join(root, "calendar/calendar.js"), "utf8");
const html = fs.readFileSync(path.join(root, "calendar/calendar.html"), "utf8");
const api = fs.readFileSync(path.join(root, "experiments/nativeCalendar/api.js"), "utf8");
const schema = JSON.parse(fs.readFileSync(path.join(root, "experiments/nativeCalendar/schema.json"), "utf8"));
assert.ok(bg.includes("async function exportCalendarDiagnostics"), "background diagnostic collector missing");
assert.ok(bg.includes("fetchRawCalendarViewForDiagnostics"), "raw Graph calendarView capture missing");
assert.ok(bg.includes("buildDiagnosticComparison"), "Graph/native comparison missing");
assert.ok(bg.includes('case "exportCalendarDiagnostics"'), "runtime diagnostic route missing");
assert.ok(api.includes("async function exportDiagnostics(extension, graphCalendarId, start"), "native cache export missing");
assert.ok(api.includes("diagnosticItemIcs"), "native ICS serialization missing");
assert.ok(schema[0].functions.some(fn => fn.name === "exportDiagnostics"), "experiment schema export missing");
assert.ok(html.includes('id="diagnosticExportBtn"'), "diagnostic export UI button missing");
assert.ok(html.includes('id="diagnosticStartDate"') && html.includes('id="diagnosticEndDate"'), "diagnostic range inputs missing");
assert.ok(ui.includes("createDiagnosticZip"), "ZIP writer missing");
assert.ok(ui.includes('name: "comparison.csv"'), "comparison CSV missing");
assert.ok(ui.includes('name: "native_range_queries.json"'), "native range queries export missing");
assert.ok(ui.includes('name: "native_calendar.ics"'), "native ICS file missing");
assert.ok(ui.includes("The export itself does NOT start a native calendar synchronization"), "no-sync safety note missing");
console.log("V2.32 diagnostic export contract OK");
