"use strict";
const fs=require("fs"),path=require("path"),assert=require("assert");
const root=path.resolve(__dirname,"..");
const bg=fs.readFileSync(path.join(root,"background.js"),"utf8");
const api=fs.readFileSync(path.join(root,"experiments/nativeCalendar/api.js"),"utf8");
const native=fs.readFileSync(path.join(root,"lib/native.js"),"utf8");
const options=fs.readFileSync(path.join(root,"options/options.js"),"utf8");
assert(bg.includes('externalImipFallback'),"config flag missing");
assert(bg.includes('externalImipPersonalPayload'),"personal-copy builder missing");
assert(bg.includes('includeAttendees: false'),"fallback must not recreate original attendees in Graph");
assert(bg.includes('nativeOperation: "external-imip-fallback"'),"fallback operation marker missing");
assert(bg.includes('externalImipMapV242'),"external UID -> Graph mapping missing");
assert(api.includes('class M365ItipTransport'),"hybrid iTIP transport missing");
assert(api.includes('CalItipEmailTransport.createInstance'),"Thunderbird email fallback missing");
assert(api.includes('responseMethod === "REPLY"'),"email fallback must be limited to RSVP replies");
assert(api.includes('X-M365-EXTERNAL-IMIP-FALLBACK'),"native fallback marker missing");
assert(native.includes('external imip invitation'),"external copy classification missing");
assert(options.includes('externalImipFallback'),"settings wiring missing");
console.log("V2.42 external iMIP fallback contract passed");
