"use strict";
const fs=require("fs"), path=require("path"), vm=require("vm"), assert=require("assert");
const root=path.resolve(__dirname,"..");
const bg=fs.readFileSync(path.join(root,"background.js"),"utf8");
const start=bg.indexOf('const NATIVE_WRITE_GUARD_TTL_MS');
const end=bg.indexOf('// V2.16: Native calendar synchronization',start);
assert.ok(start>=0 && end>start,'write guard block not found');
const sandbox={Date,Map,console};
vm.createContext(sandbox);
vm.runInContext(bg.slice(start,end)+'\nthis.rememberNativeUpsert=rememberNativeUpsert; this.rememberNativeDelete=rememberNativeDelete; this.applyRecentNativeWriteGuards=applyRecentNativeWriteGuards;',sandbox);
const cal='cal-1';
const fresh={id:'evt-1',subject:'fresh',changeKey:'new-key',lastModifiedDateTime:'2026-08-23T20:00:02Z'};
sandbox.rememberNativeUpsert(cal,fresh);
let r=sandbox.applyRecentNativeWriteGuards(cal,[]);
assert.strictEqual(r.events.length,1,'fresh create must survive missing stale calendarView row');
assert.strictEqual(r.events[0].subject,'fresh');
assert.strictEqual(r.protectedUpserts,1);
r=sandbox.applyRecentNativeWriteGuards(cal,[{id:'evt-1',subject:'old',changeKey:'old-key',lastModifiedDateTime:'2026-08-23T20:00:01Z'}]);
assert.strictEqual(r.events[0].subject,'fresh','older server row must not replace direct write');
r=sandbox.applyRecentNativeWriteGuards(cal,[{id:'evt-1',subject:'confirmed',changeKey:'new-key',lastModifiedDateTime:'2026-08-23T20:00:02Z'}]);
assert.strictEqual(r.events[0].subject,'confirmed','confirmed server row should win');
assert.strictEqual(r.remaining,0,'confirmed guard should be released');
sandbox.rememberNativeDelete(cal,'evt-2');
r=sandbox.applyRecentNativeWriteGuards(cal,[{id:'evt-2',subject:'stale-delete'}]);
assert.strictEqual(r.events.some(e=>e.id==='evt-2'),false,'stale deleted row must be filtered');
console.log('V2.24 read-after-write behavior passed');
